<a href="https://colab.research.google.com/github/Laere11/Laere11/blob/Robotics/solve_Z_in_3x3matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def get_vector_input(prompt):
    """Prompt the user for a 3D vector."""
    while True:
        try:
            values = input(f"Enter the {prompt} column values as x, y, z (comma-separated): ").strip()
            vector = np.array([float(v) for v in values.split(",")])
            if vector.shape == (3,):
                return vector
            else:
                print("Please enter exactly three values.")
        except ValueError:
            print("Invalid input. Please enter three numeric values separated by commas.")

def normalize_vector(v):
    """Normalize a 3D vector."""
    norm = np.linalg.norm(v)
    if norm == 0:
        raise ValueError("Zero vector cannot be normalized.")
    return v / norm

def main():
    print("Create a 3x3 rotation or homogeneous transformation matrix.")
    print("Note: Columns X and Y should be orthogonal unit vectors.")

    # Get user input for X and Y columns
    x_col = get_vector_input("X")
    y_col = get_vector_input("Y")

    # Normalize X and Y
    x_col = normalize_vector(x_col)
    y_col = normalize_vector(y_col)

    # Ensure orthogonality of X and Y
    if not np.isclose(np.dot(x_col, y_col), 0):
        print("Adjusting Y to be orthogonal to X.")
        y_col = y_col - np.dot(x_col, y_col) * x_col
        y_col = normalize_vector(y_col)

    # Calculate Z as the cross product of X and Y
    z_col = np.cross(x_col, y_col)

    # Form the rotation matrix
    rotation_matrix = np.column_stack((x_col, y_col, z_col))

    # Display the result
    print("\nResulting Rotation Matrix:")
    print(rotation_matrix)

    # Check if the user wants a homogeneous transformation matrix
    add_translation = input("Do you want to include a translation component? (yes/no): ").strip().lower()
    if add_translation in ['yes', 'y']:
        translation = get_vector_input("translation (tx, ty, tz)")
        homogenous_matrix = np.eye(4)
        homogenous_matrix[:3, :3] = rotation_matrix
        homogenous_matrix[:3, 3] = translation
        print("\nResulting Homogeneous Transformation Matrix:")
        print(homogenous_matrix)

if __name__ == "__main__":
    main()


Create a 3x3 rotation or homogeneous transformation matrix.
Note: Columns X and Y should be orthogonal unit vectors.
Enter the X column values as x, y, z (comma-separated): 0 0 1
Invalid input. Please enter three numeric values separated by commas.
Enter the X column values as x, y, z (comma-separated): 0, 0, 1
Enter the Y column values as x, y, z (comma-separated): -1, 0, 0

Resulting Rotation Matrix:
[[ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 1.  0.  0.]]
Do you want to include a translation component? (yes/no): yes
Enter the translation (tx, ty, tz) column values as x, y, z (comma-separated): 1, 0, 0

Resulting Homogeneous Transformation Matrix:
[[ 0. -1.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
