<a href="https://colab.research.google.com/github/Laere11/Laere11/blob/main/XYvector_IN_Zvector_OUT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prompts the user for the X and Y vector values and then computes the Z vector information.  Then it displays the 3x3 matrix using the convention of axis represented as columns.

In [1]:
import numpy as np

def main():
    # Prompt for x-axis vector components
    x_input = input("Enter the 3 components of the x-axis vector (separated by spaces): ")
    x_components = list(map(float, x_input.split()))
    if len(x_components) != 3:
        print("Error: Please enter exactly 3 numbers for the x-axis vector.")
        return

    # Prompt for y-axis vector components
    y_input = input("Enter the 3 components of the y-axis vector (separated by spaces): ")
    y_components = list(map(float, y_input.split()))
    if len(y_components) != 3:
        print("Error: Please enter exactly 3 numbers for the y-axis vector.")
        return

    # Convert lists to numpy arrays for computation
    x = np.array(x_components)
    y = np.array(y_components)

    # Compute the z-axis as the cross product of x and y (ensuring a right-handed system)
    z = np.cross(x, y)
    print("\nThe computed z-axis vector (x × y) is:", z)

    # Form the 3x3 matrix with the axes as columns
    matrix = np.column_stack((x, y, z))
    print("\nThe 3x3 matrix with axes as columns is:")
    print(matrix)

if __name__ == "__main__":
    main()


Enter the 3 components of the x-axis vector (separated by spaces): 0 0 1
Enter the 3 components of the y-axis vector (separated by spaces): -1 0 0

The computed z-axis vector (x × y) is: [ 0. -1.  0.]

The 3x3 matrix with axes as columns is:
[[ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 1.  0.  0.]]
